# Generated by Django 4.2.4 on 2023-12-02 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Mathematics', 'Mathematics'), ('History', 'History'), ('Literature', 'Literature'), ('Languages', 'Languages'), ('Arts', 'Arts'), ('Health and Medicine', 'Health & Medicine'), ('Programming', 'Programming'), ('Misc', 'Misc.')], default='Misc', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
