# Generated by Django 5.0.6 on 2024-07-09 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0002_contact_webimgs_deck_card_note_delete_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 9, 16, 49, 116734, tzinfo=datetime.timezone.utc)),
        ),
    ]
