# Generated by Django 4.2.4 on 2023-12-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0003_contact_webimgs_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='authentication_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
