# Generated by Django 4.2.4 on 2023-12-19 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0004_alter_user_profile_authentication_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Mathematics', 'Mathematics'), ('History', 'History'), ('Literature', 'Literature'), ('Languages', 'Languages'), ('Arts', 'Arts'), ('Health and Medicine', 'Health & Medicine'), ('Programming', 'Programming'), ('Lifeskills', 'Lifeskills/Self Help'), ('CLEP', 'CLEP Exams'), ('Misc', 'Misc.')], default='Misc', max_length=25),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapp.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
