# Generated by Django 4.2.4 on 2023-12-20 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0005_alter_deck_category_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 0, 38, 34, 736865, tzinfo=datetime.timezone.utc)),
        ),
    ]
