# Generated by Django 5.0.6 on 2024-07-09 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0005_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 5, 56, 59, 410030, tzinfo=datetime.timezone.utc)),
        ),
    ]
