# Generated by Django 4.2.4 on 2023-12-20 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0012_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 1, 7, 6, 668297, tzinfo=datetime.timezone.utc)),
        ),
    ]
