# Generated by Django 4.2.4 on 2023-12-20 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0014_alter_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 1, 21, 35, 891872, tzinfo=datetime.timezone.utc)),
        ),
    ]
