# Generated by Django 4.2.4 on 2023-12-20 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0015_note_title_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 1, 28, 27, 207, tzinfo=datetime.timezone.utc)),
        ),
    ]
