# Generated by Django 5.0.6 on 2024-07-04 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0018_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 6, 7, 1, 114171, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
