# Generated by Django 5.0.6 on 2024-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='ilovecookbooks_profile_pic',
            field=models.ImageField(default='none', upload_to='ilovecookbooks_profile_images'),
        ),
    ]
