# Generated by Django 5.0.6 on 2024-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilovecookbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuserprofilepicture',
            name='image',
            field=models.ImageField(upload_to='flashcards_profile_imgs/'),
        ),
    ]
